export ADDITIONAL_LDFLAGS = -Wl,-segalign,4000

export TARGET = iphone:latest:7.0
export ARCHS = arm64 arm64e 
export SDKVERSION = 11.2
export SYSROOT = $(THEOS)/sdks/iPhoneOS11.2.sdk

include Makefile.common
